import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms & Conditions',
  description:
    'WarWatch.World Terms and Conditions — rules of use, disclaimers, and limitations of liability for this free open-source conflict tracking platform.',
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <nav className="text-xs text-gray-500 mb-8">
        <Link href="/" className="hover:text-gray-300 transition-colors">Home</Link>
        <span className="mx-1">/</span>
        <span>Terms & Conditions</span>
      </nav>

      <h1 className="text-3xl font-bold text-white mb-2">Terms &amp; Conditions</h1>
      <p className="text-gray-500 text-sm mb-10">Last updated: March 30, 2026</p>

      <div className="space-y-8 text-gray-300 leading-relaxed text-sm">

        <section>
          <p>
            By accessing and using WarWatch.World (&quot;the Service&quot;), you agree to be bound by these Terms &amp; Conditions. If you do not agree, please discontinue use of the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">1. Nature of the Service</h2>
          <p>
            WarWatch.World is a free, open-source data aggregation platform that collects and presents publicly available information about active global conflicts and security situations. The Service is provided on an &quot;as is&quot; basis for informational purposes only.
          </p>
          <p className="mt-2 text-gray-400">
            WarWatch is <strong className="text-gray-300">not</strong> a news organization, intelligence service, government agency, financial service, or humanitarian organization. Information on this platform must not be used as the sole basis for:
          </p>
          <ul className="list-disc list-inside space-y-1 mt-2 text-gray-400">
            <li>Operational security decisions</li>
            <li>Financial or investment decisions</li>
            <li>Humanitarian response planning</li>
            <li>Legal proceedings</li>
            <li>Any decision with significant real-world consequences</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">2. Accuracy Disclaimer</h2>
          <p className="text-gray-400">
            Conflict data is sourced from publicly available news reports and synthesized using AI. We make reasonable efforts to ensure accuracy but cannot guarantee that all information is current, complete, or error-free. Active conflicts evolve rapidly; information may be outdated by the time you read it.
          </p>
          <p className="mt-2 text-gray-400">
            Always verify critical information through authoritative primary sources including official government communications, UN agencies, and recognized international organizations.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">3. Political Neutrality</h2>
          <p className="text-gray-400">
            WarWatch.World presents conflict data without taking political positions. The presence of a conflict in our database, its severity classification, or any description of events does not constitute an endorsement, condemnation, or political statement regarding any party, government, armed group, or ideology involved.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">4. AI-Generated Content</h2>
          <p className="text-gray-400">
            The AI Analyst chat and daily intelligence reports are generated by AI (Anthropic Claude). AI-generated content may contain errors, omissions, or outdated information. Such content is explicitly labeled and should be treated as a starting point for research, not as authoritative analysis. AI responses do not represent the views of WarWatch.World contributors.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">5. Acceptable Use</h2>
          <p>You agree not to use the Service to:</p>
          <ul className="list-disc list-inside space-y-1 mt-2 text-gray-400">
            <li>Spread disinformation or deliberately misrepresent conflict data</li>
            <li>Harass, threaten, or incite violence against any individual or group</li>
            <li>Scrape or crawl the Service in a way that impairs its availability to others</li>
            <li>Circumvent any technical measures protecting the Service</li>
            <li>Use the Service for any purpose that violates applicable law</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">6. Open Source License</h2>
          <p className="text-gray-400">
            The WarWatch.World codebase is licensed under the{' '}
            <a href="https://github.com/nitinchhabria89/WarWatch.World/blob/main/LICENSE" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300">
              MIT License
            </a>. You are free to use, copy, modify, and distribute the code, subject to the terms of that license. Data sourced from third parties (NewsAPI, etc.) is subject to those providers&apos; own terms of service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">7. Advertising</h2>
          <p className="text-gray-400">
            This Service displays advertisements through Google AdSense to cover operational costs. Advertisements are served by Google and are not endorsements by WarWatch.World of any advertiser, product, or service. See our{' '}
            <Link href="/monetization-policy" className="text-blue-400 hover:text-blue-300">Monetization Policy</Link>{' '}
            for full details.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">8. Limitation of Liability</h2>
          <p className="text-gray-400">
            To the maximum extent permitted by applicable law, WarWatch.World and its contributors shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of, or inability to use, the Service or any information contained therein. This includes, without limitation, damages arising from decisions made based on information provided by the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">9. Indemnification</h2>
          <p className="text-gray-400">
            You agree to indemnify and hold harmless WarWatch.World contributors from any claims, damages, or expenses arising from your use of the Service or violation of these Terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">10. Changes to Terms</h2>
          <p className="text-gray-400">
            We reserve the right to modify these Terms at any time. Changes are effective upon posting. The &quot;Last updated&quot; date at the top reflects the most recent revision. Continued use of the Service after changes constitutes acceptance.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">11. Governing Law</h2>
          <p className="text-gray-400">
            These Terms shall be governed by and construed in accordance with applicable law. Any disputes will be resolved in the appropriate jurisdiction where the project maintainers are located.
          </p>
        </section>

        <div className="border-t border-white/10 pt-6 text-xs text-gray-600">
          <div className="flex flex-wrap gap-4">
            <Link href="/editorial-policy" className="hover:text-gray-400 transition-colors">Editorial Policy</Link>
            <Link href="/privacy-policy" className="hover:text-gray-400 transition-colors">Privacy Policy</Link>
            <Link href="/monetization-policy" className="hover:text-gray-400 transition-colors">Monetization Policy</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
