import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { getReport, listReportDates } from '@/lib/conflicts';
import AdUnit from '@/components/AdUnit';
import { formatDate } from '@/lib/utils';

interface Props {
  params: { date: string };
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const report = getReport(params.date);
  if (!report) return { title: 'Report Not Found' };

  return {
    title: `${formatDate(report.date)} — ${report.headline}`,
    description: report.summary.slice(0, 160),
    openGraph: {
      type: 'article',
      publishedTime: report.generatedAt,
      title: report.headline,
      description: report.summary.slice(0, 160),
    },
  };
}

export function generateStaticParams() {
  return listReportDates().map((date) => ({ date }));
}

export default function ReportPage({ params }: Props) {
  const report = getReport(params.date);
  if (!report) notFound();

  return (
    <div className="max-w-screen-xl mx-auto px-4 py-8">
      {/* Billboard */}
      <div className="flex justify-center mb-6">
        <AdUnit slot="report-billboard" style={{ width: 728, height: 90 }} className="hidden md:block" />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2">
          {/* Breadcrumb */}
          <nav className="text-xs text-gray-500 mb-4">
            <Link href="/reports" className="hover:text-gray-300 transition-colors">Reports</Link>
            <span className="mx-1">/</span>
            <span>{formatDate(report.date)}</span>
          </nav>

          <article>
            <header className="mb-6">
              <p className="text-xs text-blue-400 uppercase tracking-wide mb-2">
                Daily Intelligence Briefing · {formatDate(report.date)}
              </p>
              <h1 className="text-2xl font-bold text-white mb-3">{report.headline}</h1>
              <p className="text-gray-300 text-base leading-relaxed">{report.summary}</p>
            </header>

            {/* In-content ad */}
            <div className="flex justify-center my-6">
              <AdUnit slot="report-in-content" style={{ width: 300, height: 250 }} />
            </div>

            {/* Regional Breakdowns */}
            <section className="space-y-4 mb-8">
              <h2 className="text-lg font-semibold text-white">Regional Breakdown</h2>
              {report.regions.map((region) => (
                <div key={region.name} className="bg-[#111827] border border-white/10 rounded-lg p-4">
                  <h3 className="font-semibold text-gray-200 text-sm mb-2">{region.name}</h3>
                  <p className="text-gray-400 text-sm leading-relaxed">{region.content}</p>
                </div>
              ))}
            </section>

            {/* Market Analysis */}
            <section className="bg-[#111827] border border-white/10 rounded-lg p-4 mb-6">
              <h2 className="text-sm font-semibold text-gray-200 mb-2 flex items-center gap-2">
                <span>📈</span> Market Impact Analysis
              </h2>
              <p className="text-gray-400 text-sm leading-relaxed">{report.marketAnalysis}</p>
            </section>

            <div className="flex items-center justify-between text-xs text-gray-600 border-t border-white/10 pt-4">
              <span>Generated by Claude AI · {new Date(report.generatedAt).toUTCString()}</span>
              <Link href="/reports" className="text-blue-400 hover:text-blue-300 transition-colors">
                ← All Reports
              </Link>
            </div>
          </article>
        </div>

        {/* Sidebar */}
        <div className="space-y-4">
          <AdUnit slot="report-sidebar" style={{ width: 300, height: 600 }} />
          <div className="bg-[#111827] border border-white/10 rounded-lg p-4">
            <p className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-3">Disclaimer</p>
            <p className="text-xs text-gray-500 leading-relaxed">
              This report is AI-generated using publicly available conflict data. It is for informational purposes only.
              Do not rely on this for operational decisions. Always verify with authoritative sources.
            </p>
          </div>
        </div>
      </div>

      {/* JSON-LD */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'NewsArticle',
            headline: report.headline,
            datePublished: report.generatedAt,
            dateModified: report.generatedAt,
            description: report.summary,
            publisher: {
              '@type': 'Organization',
              name: 'WarWatch.World',
              url: process.env.NEXT_PUBLIC_SITE_URL,
            },
          }),
        }}
      />
    </div>
  );
}
